# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recttestdialog.ui'
#
# Created by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_RectTestDialog(object):
    def setupUi(self, RectTestDialog):
        RectTestDialog.setObjectName(_fromUtf8("RectTestDialog"))
        RectTestDialog.resize(620, 500)
        self.verticalLayout = QtGui.QVBoxLayout(RectTestDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget = QtGui.QWidget(RectTestDialog)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget1 = QtGui.QWidget(self.widget)
        self.widget1.setMinimumSize(QtCore.QSize(200, 0))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout = QtGui.QGridLayout(self.widget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.heightInput = QtGui.QSlider(self.widget1)
        self.heightInput.setMaximum(400)
        self.heightInput.setProperty(_fromUtf8("value"), 100)
        self.heightInput.setOrientation(QtCore.Qt.Horizontal)
        self.heightInput.setObjectName(_fromUtf8("heightInput"))
        self.gridLayout.addWidget(self.heightInput, 3, 1, 1, 1)
        self.xInput = QtGui.QSlider(self.widget1)
        self.xInput.setMaximum(500)
        self.xInput.setProperty(_fromUtf8("value"), 100)
        self.xInput.setOrientation(QtCore.Qt.Horizontal)
        self.xInput.setObjectName(_fromUtf8("xInput"))
        self.gridLayout.addWidget(self.xInput, 0, 1, 1, 1)
        self.xLabel = QtGui.QLabel(self.widget1)
        self.xLabel.setObjectName(_fromUtf8("xLabel"))
        self.gridLayout.addWidget(self.xLabel, 0, 0, 1, 1)
        self.yInput = QtGui.QSlider(self.widget1)
        self.yInput.setMaximum(500)
        self.yInput.setProperty(_fromUtf8("value"), 100)
        self.yInput.setOrientation(QtCore.Qt.Horizontal)
        self.yInput.setInvertedAppearance(False)
        self.yInput.setObjectName(_fromUtf8("yInput"))
        self.gridLayout.addWidget(self.yInput, 1, 1, 1, 1)
        self.heightLabel = QtGui.QLabel(self.widget1)
        self.heightLabel.setObjectName(_fromUtf8("heightLabel"))
        self.gridLayout.addWidget(self.heightLabel, 3, 0, 1, 1)
        self.widthLabel = QtGui.QLabel(self.widget1)
        self.widthLabel.setObjectName(_fromUtf8("widthLabel"))
        self.gridLayout.addWidget(self.widthLabel, 2, 0, 1, 1)
        self.yLabel = QtGui.QLabel(self.widget1)
        self.yLabel.setObjectName(_fromUtf8("yLabel"))
        self.gridLayout.addWidget(self.yLabel, 1, 0, 1, 1)
        self.widthInput = QtGui.QSlider(self.widget1)
        self.widthInput.setMaximum(400)
        self.widthInput.setProperty(_fromUtf8("value"), 100)
        self.widthInput.setOrientation(QtCore.Qt.Horizontal)
        self.widthInput.setObjectName(_fromUtf8("widthInput"))
        self.gridLayout.addWidget(self.widthInput, 2, 1, 1, 1)
        self.axis3dXLabel = QtGui.QLabel(self.widget1)
        self.axis3dXLabel.setObjectName(_fromUtf8("axis3dXLabel"))
        self.gridLayout.addWidget(self.axis3dXLabel, 6, 0, 1, 1)
        self.colorLabel = QtGui.QLabel(self.widget1)
        self.colorLabel.setObjectName(_fromUtf8("colorLabel"))
        self.gridLayout.addWidget(self.colorLabel, 4, 0, 1, 1)
        self.axis3dYInput = QtGui.QSlider(self.widget1)
        self.axis3dYInput.setMaximum(199)
        self.axis3dYInput.setOrientation(QtCore.Qt.Horizontal)
        self.axis3dYInput.setObjectName(_fromUtf8("axis3dYInput"))
        self.gridLayout.addWidget(self.axis3dYInput, 7, 1, 1, 1)
        self.axis3dYLabel = QtGui.QLabel(self.widget1)
        self.axis3dYLabel.setObjectName(_fromUtf8("axis3dYLabel"))
        self.gridLayout.addWidget(self.axis3dYLabel, 7, 0, 1, 1)
        self.axis3dXInput = QtGui.QSlider(self.widget1)
        self.axis3dXInput.setMaximum(199)
        self.axis3dXInput.setOrientation(QtCore.Qt.Horizontal)
        self.axis3dXInput.setObjectName(_fromUtf8("axis3dXInput"))
        self.gridLayout.addWidget(self.axis3dXInput, 6, 1, 1, 1)
        self.angleLabel = QtGui.QLabel(self.widget1)
        self.angleLabel.setObjectName(_fromUtf8("angleLabel"))
        self.gridLayout.addWidget(self.angleLabel, 5, 0, 1, 1)
        self.colorInput = QtGui.QLineEdit(self.widget1)
        self.colorInput.setObjectName(_fromUtf8("colorInput"))
        self.gridLayout.addWidget(self.colorInput, 4, 1, 1, 1)
        self.angleInput = QtGui.QSlider(self.widget1)
        self.angleInput.setMaximum(360)
        self.angleInput.setOrientation(QtCore.Qt.Horizontal)
        self.angleInput.setObjectName(_fromUtf8("angleInput"))
        self.gridLayout.addWidget(self.angleInput, 5, 1, 1, 1)
        self.axis3dZLabel = QtGui.QLabel(self.widget1)
        self.axis3dZLabel.setObjectName(_fromUtf8("axis3dZLabel"))
        self.gridLayout.addWidget(self.axis3dZLabel, 8, 0, 1, 1)
        self.axis3dZInput = QtGui.QSlider(self.widget1)
        self.axis3dZInput.setMaximum(199)
        self.axis3dZInput.setOrientation(QtCore.Qt.Horizontal)
        self.axis3dZInput.setObjectName(_fromUtf8("axis3dZInput"))
        self.gridLayout.addWidget(self.axis3dZInput, 8, 1, 1, 1)
        self.xInput2 = QtGui.QSpinBox(self.widget1)
        self.xInput2.setMaximum(500)
        self.xInput2.setObjectName(_fromUtf8("xInput2"))
        self.gridLayout.addWidget(self.xInput2, 0, 2, 1, 1)
        self.yInput2 = QtGui.QSpinBox(self.widget1)
        self.yInput2.setMaximum(500)
        self.yInput2.setObjectName(_fromUtf8("yInput2"))
        self.gridLayout.addWidget(self.yInput2, 1, 2, 1, 1)
        self.widthInput2 = QtGui.QSpinBox(self.widget1)
        self.widthInput2.setMaximum(400)
        self.widthInput2.setObjectName(_fromUtf8("widthInput2"))
        self.gridLayout.addWidget(self.widthInput2, 2, 2, 1, 1)
        self.heightInput2 = QtGui.QSpinBox(self.widget1)
        self.heightInput2.setMaximum(400)
        self.heightInput2.setObjectName(_fromUtf8("heightInput2"))
        self.gridLayout.addWidget(self.heightInput2, 3, 2, 1, 1)
        self.angleInput2 = QtGui.QSpinBox(self.widget1)
        self.angleInput2.setMaximum(360)
        self.angleInput2.setObjectName(_fromUtf8("angleInput2"))
        self.gridLayout.addWidget(self.angleInput2, 5, 2, 1, 1)
        self.axis3dXInput2 = QtGui.QDoubleSpinBox(self.widget1)
        self.axis3dXInput2.setMaximum(1.99)
        self.axis3dXInput2.setSingleStep(0.01)
        self.axis3dXInput2.setObjectName(_fromUtf8("axis3dXInput2"))
        self.gridLayout.addWidget(self.axis3dXInput2, 6, 2, 1, 1)
        self.axis3dYInput2 = QtGui.QDoubleSpinBox(self.widget1)
        self.axis3dYInput2.setMaximum(1.99)
        self.axis3dYInput2.setSingleStep(0.01)
        self.axis3dYInput2.setObjectName(_fromUtf8("axis3dYInput2"))
        self.gridLayout.addWidget(self.axis3dYInput2, 7, 2, 1, 1)
        self.axis3dZInput2 = QtGui.QDoubleSpinBox(self.widget1)
        self.axis3dZInput2.setMaximum(1.99)
        self.axis3dZInput2.setSingleStep(0.01)
        self.axis3dZInput2.setObjectName(_fromUtf8("axis3dZInput2"))
        self.gridLayout.addWidget(self.axis3dZInput2, 8, 2, 1, 1)
        self.horizontalLayout.addWidget(self.widget1)
        self.qmlView = QtDeclarative.QDeclarativeView(self.widget)
        self.qmlView.setMinimumSize(QtCore.QSize(400, 400))
        self.qmlView.setObjectName(_fromUtf8("qmlView"))
        self.horizontalLayout.addWidget(self.qmlView)
        self.verticalLayout.addWidget(self.widget)
        self.buttonBox = QtGui.QDialogButtonBox(RectTestDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(RectTestDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), RectTestDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), RectTestDialog.reject)
        QtCore.QObject.connect(self.xInput, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.xInput2.setValue)
        QtCore.QObject.connect(self.xInput2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.xInput.setValue)
        QtCore.QObject.connect(self.yInput, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.yInput2.setValue)
        QtCore.QObject.connect(self.yInput2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.yInput.setValue)
        QtCore.QObject.connect(self.widthInput, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.widthInput2.setValue)
        QtCore.QObject.connect(self.widthInput2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.widthInput.setValue)
        QtCore.QObject.connect(self.angleInput, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.angleInput2.setValue)
        QtCore.QObject.connect(self.angleInput2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.angleInput.setValue)
        QtCore.QObject.connect(self.heightInput, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.heightInput2.setValue)
        QtCore.QObject.connect(self.heightInput2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.heightInput.setValue)
        QtCore.QMetaObject.connectSlotsByName(RectTestDialog)

    def retranslateUi(self, RectTestDialog):
        RectTestDialog.setWindowTitle(QtGui.QApplication.translate("RectTestDialog", "Rectangle Tester", None, QtGui.QApplication.UnicodeUTF8))
        self.xLabel.setText(QtGui.QApplication.translate("RectTestDialog", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.heightLabel.setText(QtGui.QApplication.translate("RectTestDialog", "height", None, QtGui.QApplication.UnicodeUTF8))
        self.widthLabel.setText(QtGui.QApplication.translate("RectTestDialog", "width", None, QtGui.QApplication.UnicodeUTF8))
        self.yLabel.setText(QtGui.QApplication.translate("RectTestDialog", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.axis3dXLabel.setText(QtGui.QApplication.translate("RectTestDialog", "3d x", None, QtGui.QApplication.UnicodeUTF8))
        self.colorLabel.setText(QtGui.QApplication.translate("RectTestDialog", "color", None, QtGui.QApplication.UnicodeUTF8))
        self.axis3dYLabel.setText(QtGui.QApplication.translate("RectTestDialog", "3d y", None, QtGui.QApplication.UnicodeUTF8))
        self.angleLabel.setText(QtGui.QApplication.translate("RectTestDialog", "angle", None, QtGui.QApplication.UnicodeUTF8))
        self.axis3dZLabel.setText(QtGui.QApplication.translate("RectTestDialog", "3d z", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtDeclarative
